<?php
# This file was automatically generated by the MediaWiki 1.44.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

# ==== Load .env ====
$IP = __DIR__;
require_once $IP . '/vendor/autoload.php';
$dotenv = Dotenv\Dotenv::createImmutable($IP);
$dotenv->safeLoad();

function envr($key, $default = null) {
    return $_ENV[$key] ?? $_SERVER[$key] ?? getenv($key) ?: $default;
}
# ====================

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "WikiDocs";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://wiki-docs.local";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/logo.png",
	'icon' => "$wgResourceBasePath/resources/assets/logo.png",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "";
$wgPasswordSender = "";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings (from .env)
$wgDBtype     = (envr('DB_DRIVER','postgres') === 'pgsql') ? 'postgres' : envr('DB_DRIVER','postgres');
$wgDBserver   = envr('DB_HOST', '127.0.0.1');
$wgDBname     = envr('DB_NAME', '');
$wgDBuser     = envr('DB_USER', '');
$wgDBpassword = envr('DB_PASS', '');
$wgDBport     = envr('DB_PORT', '5432');

# Postgres specific
$wgDBssl      = false;
$wgDBmwschema = 'mediawiki';

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "ru";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = envr( 'WIKI_SECRET_KEY' );
if ( !$wgSecretKey ) {
        throw new RuntimeException('WIKI_SECRET_KEY is not configured');
}

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = envr( 'WIKI_UPGRADE_KEY' );
if ( !$wgUpgradeKey ) {
        throw new RuntimeException('WIKI_UPGRADE_KEY is not configured');
}

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
# Единая тема и опции по умолчанию
# ==== Vector 2022: тёмная тема по умолчанию для всех ====
$wgDefaultSkin = 'vector-2022';
$wgDefaultUserOptions['skin'] = 'vector-2022';
$wgDefaultUserOptions['skin-theme'] = 'dark';          
$wgDefaultUserOptions['vector-theme'] = 'vector-dark'; 
$wgDefaultUserOptions['vector-2022-theme'] = 'dark';   

# Полная ширина (убираем ограничение)
$wgDefaultUserOptions['vector-limited-width'] = 0;

# Подключаем скины (минимум Vector нужен)
wfLoadSkin( 'Vector' );
# Остальные опционально:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );



# End of automatically generated settings.
# Add more configuration options below.
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'PdfHandler' );           
wfLoadExtension( 'ConfirmEdit' );          
wfLoadExtension( 'SpamBlacklist' );         

$wgMemCachedServers = [ '127.0.0.1:11211' ];
$wgMainCacheType    = CACHE_MEMCACHED;
$wgParserCacheType  = CACHE_MEMCACHED;
$wgMessageCacheType = CACHE_MEMCACHED;

# === Файлы/загрузки ===
$wgEnableUploads  = true;
$wgFileExtensions = [ 'png','jpg','jpeg','gif','webp','svg','pdf' ];

# === Админка и фильтры ===
wfLoadExtension( 'Lockdown' );
wfLoadExtension( 'AbuseFilter' );

$wgSpecialPageLockdown = [
    'Userrights' => [ 'sysop', 'bureaucrat' ], 
    'Listusers'  => [ 'sysop', 'bureaucrat' ], 
    'Upload'     => [ 'sysop', 'editor' ],     
];

# === Права групп ===

# Гости (анонимы) — только чтение
$wgGroupPermissions['*']['read']          = true;
$wgGroupPermissions['*']['edit']          = false;
$wgGroupPermissions['*']['createpage']    = false;
$wgGroupPermissions['*']['createtalk']    = false;
$wgGroupPermissions['*']['upload']        = false;
$wgGroupPermissions['*']['move']          = false;
$wgGroupPermissions['*']['createaccount'] = true;

# Базовые залогиненные (user, autoconfirmed) — НИЧЕГО с контентом
foreach ( [ 'user', 'autoconfirmed' ] as $g ) {
    $wgGroupPermissions[$g]['read']               = true;

    # прямые контентные действия — запрет
    $wgGroupPermissions[$g]['edit']               = false;
    $wgGroupPermissions[$g]['createpage']         = false;
    $wgGroupPermissions[$g]['createtalk']         = false;
    $wgGroupPermissions[$g]['upload']             = false;
    $wgGroupPermissions[$g]['reupload']           = false;
    $wgGroupPermissions[$g]['reupload-shared']    = false;
    $wgGroupPermissions[$g]['reupload-own']       = false;
    $wgGroupPermissions[$g]['move']               = false;
    $wgGroupPermissions[$g]['movefile']           = false;
    $wgGroupPermissions[$g]['move-subpages']      = false;
    $wgGroupPermissions[$g]['move-rootuserpages'] = false;
    $wgGroupPermissions[$g]['move-categorypages'] = false;

    # косвенные права — тоже в ноль
    $wgGroupPermissions[$g]['minoredit']          = false;
    $wgGroupPermissions[$g]['changetags']         = false;
    $wgGroupPermissions[$g]['applychangetags']    = false;
    $wgGroupPermissions[$g]['editcontentmodel']   = false;
    $wgGroupPermissions[$g]['sendemail']        = false;
    $wgGroupPermissions[$g]['spamblacklistlog'] = false;

    # свой профиль — можно править
    $wgGroupPermissions[$g]['editmyoptions']      = true;
    $wgGroupPermissions[$g]['editmyprivateinfo']  = true;
    $wgGroupPermissions[$g]['editmyusercss']      = true;
    $wgGroupPermissions[$g]['editmyuserjs']       = true;
    $wgGroupPermissions[$g]['editmyuserjson']     = true;
}

$wgGroupPermissions['autoconfirmed']['editsemiprotected'] = false;

# Редактор — ведёт контент, без админских полномочий
$wgGroupPermissions['editor']['read']               = true;
$wgGroupPermissions['editor']['edit']               = true;
$wgGroupPermissions['editor']['createpage']         = true;
$wgGroupPermissions['editor']['createtalk']         = true;
$wgGroupPermissions['editor']['upload']             = true;
$wgGroupPermissions['editor']['reupload']           = false;
$wgGroupPermissions['editor']['reupload-shared']    = false;
$wgGroupPermissions['editor']['reupload-own']       = true;

$wgGroupPermissions['editor']['delete']             = false;
$wgGroupPermissions['editor']['undelete']           = false;
$wgGroupPermissions['editor']['protect']            = false;
$wgGroupPermissions['editor']['move']               = false;
$wgGroupPermissions['editor']['movefile']           = false;
$wgGroupPermissions['editor']['move-subpages']      = false;
$wgGroupPermissions['editor']['move-rootuserpages'] = false;
$wgGroupPermissions['editor']['move-categorypages'] = false;
$wgGroupPermissions['editor']['userrights']         = false;
$wgGroupPermissions['editor']['abusefilter-exempt'] = false;

# Админ — полный доступ
$wgGroupPermissions['sysop']['edit']                = true;
$wgGroupPermissions['sysop']['createpage']          = true;
$wgGroupPermissions['sysop']['createtalk']          = true;
$wgGroupPermissions['sysop']['upload']              = true;
$wgGroupPermissions['sysop']['reupload']            = true;
$wgGroupPermissions['sysop']['reupload-shared']     = true;
$wgGroupPermissions['sysop']['reupload-own']        = true;
$wgGroupPermissions['sysop']['delete']              = true;
$wgGroupPermissions['sysop']['undelete']            = true;
$wgGroupPermissions['sysop']['protect']             = true;
$wgGroupPermissions['sysop']['move']                = true;
$wgGroupPermissions['sysop']['movefile']            = true;
$wgGroupPermissions['sysop']['move-subpages']       = true;
$wgGroupPermissions['sysop']['move-rootuserpages']  = true;
$wgGroupPermissions['sysop']['move-categorypages']  = true;
$wgGroupPermissions['sysop']['userrights']          = true;
$wgGroupPermissions['sysop']['createaccount']       = true;

# Права для интерфейса AbuseFilter админу
$wgGroupPermissions['sysop']['abusefilter-view']        = true;
$wgGroupPermissions['sysop']['abusefilter-log']         = true;
$wgGroupPermissions['sysop']['abusefilter-modify']      = true;
$wgGroupPermissions['sysop']['abusefilter-revert']      = true;
$wgGroupPermissions['sysop']['abusefilter-private']     = true;
$wgGroupPermissions['sysop']['abusefilter-exempt']      = true;

use MediaWiki\MediaWikiServices;
use MediaWiki\Deferred\DeferredUpdates;

$wgHooks['LocalUserCreated'][] = static function ( $userIdentity, $autocreated ) {
    if ( $autocreated ) {
        return;
    }
    // Назначаем группу после фиксации транзакции
    DeferredUpdates::addCallableUpdate( static function () use ( $userIdentity ) {
        MediaWikiServices::getInstance()
            ->getUserGroupManager()
            ->addUserToGroup( $userIdentity, 'editor' );
    } );
};
